---
title: "Agate - liste des indicateurs"
author: "Nicolas Kempf"
date: "29/11/2018"
output: html_document
---

```{r,include=FALSE}
# Packages necessaires
# library(tidyverse) # transformation des données
library(DT) # Affichage d'un tableau intéractif

# I. Construction de la base de données
#--------------------------------------------------------------------------------------------------------------------------------
indicateurs <- read.csv(file = "Agate - liste indicateurs.csv",header = TRUE,sep = ";")

```


Les indicateurs proviennent des sources suivantes :

* Recensement de la population exploitation principale, niveau individu et logement
* Fichiers fiscaux géolocalisés (Filosofi) côté niveau de vie

```{r,echo=FALSE}
datatable(indicateurs,
          extensions = 'Buttons',
          options = list(
            scrollX = TRUE,
            # fixedColumns = TRUE,
            # autoWidth = TRUE,
            ordering = TRUE,
            dom = 'lBfrtip',
            buttons = c(I('colvis'),'excel', 'pdf')),
          rownames= FALSE,
          class = "display" #if you want to modify via .css
)
```

# A venir

* Indicateurs de décomposition du niveau de vie
* Indicateurs issus d'autres sources : BPE, CAF, FIDELI, etc.






