---
title: "Row Orientation"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

    ```{r,include=FALSE}

# Préparation des données
#------------------------

# Packages necessaires
library(flexdashboard) # Tableaux de bord statiques
library(plotly) # Graphiques interactifs
library(tidyverse) # transformation des données

# Fonctions supplémentaires
source("../Plotly/Agate - plotly graphes fonctions_v3.R")

# Import des bases
load("../../Data/Statistiques Zonage/StatRegCom_rp14_filo14.RData")
communes <- statCom_rp14_filo14
region <- statReg_rp14_filo14

```
    
    
    
    
    
Row
-------------------------------------
    
### Zonage
```{r}
valueBox("Test", icon = "fa-pencil",color = "yellow")
```
   
Row
-------------------------------------
    
### Distribution du niveau de vie

```{r}
idZonage.com <- "97201"
idZonage.dep <- "972"

# Commune
varKeep <- c("com")
reg.boxplot <- df_boxplot(df = communes$tFilo.I.1,varKeep = varKeep) 
y <- as.character(reg.boxplot[reg.boxplot$com == idZonage.com,!colnames(reg.boxplot) %in% varKeep])
# Region
varKeep <- c("dep")
reg.boxplot <- df_boxplot(df = region$tFilo.I.1,varKeep = varKeep)
z <-  as.character(reg.boxplot[reg.boxplot$dep == idZonage.dep,!colnames(reg.boxplot) %in% varKeep])
name.comp <- idZonage.dep

# Boxplot
plot_ly() %>% 
  add_trace(y=y, name=idZonage.com , type="box") %>% 
  add_trace(y=z, name= name.comp, type="box") %>%
  layout(autosize=TRUE, boxmode="group", hovermode="closest", 
         showlegend=TRUE,
         xaxis = list(
           autorange = TRUE, 
           showticklabels = FALSE, 
           type = "category"),
         yaxis = list(
           autorange = TRUE, 
           type = "linear")
  )
```