---
title: "Note Qualite"
author: "Baptiste Raimbaud"
date: "1 juillet 2019"
output: html_document
---



# Qualité des estimateurs dans Agate

La méthode d’estimation se base sur les travaux sur la qualité du RP (DELTA, 2017).

## Plan de Sondage :
`Probabilité = 1` pour les adresses situées dans les petites communes. Et quelques adresses de grandes communes.

`Probabilité = 0.4` pour les adresses de grandes communes.

Les poids sont calés en utilisant le nombre de logements (variable appelée X).

On considère que les adresses sondées sont celles dont le poids après traitement est supérieur à 1.75.
	
# I. Estimation simple d’un total et variance associée.

L’estimation du total $T_Y$ se fait par l’intermédiaire de  :

\begin{equation}
\tag{1}
{\hat{T}}_Y = \sum_{cg} \sum_{i \in S_{c g}}  y_i  \times  IPOND 
\end{equation}

où  $S_{c g}$ est l'ensemble des adresses sondées dans une communes 'c' et appartenant au groupe de rotation 'g' ; la variance associée est : 

(2) $V( {\hat T}_Y )  = \sum_{cg} {{1-f} \over f²} \sum_{i \in S_{c g}} (y_i  -  R x_i)²$ où $R  =  {{\hat T }_Y \over {{\hat T }_X}}$ (DELTA, 2017).

L’estimation de $T_Y$ sur un sous-domaine est équivalent à l’estimation de $T_Z$ où $Z = Y ·  1_{[zone]}$. (DELTA, 2017).

Ainsi : ${\hat T}_Z = \sum_{cg} \sum_{i \in S_{c g}} z_i \times  IPOND$   
et   $V( {\hat T}_Z ) = \sum_{cg} {{1-f} \over {f²}} \sum_{i \in S_{c g}} (z_i - R x_i)²$ où $R = {{\hat T }_Z \over {{\hat T }_X}}$

Le RP étant fait de manière indépendante entre chaque commune et chaque groupe de rotation, la variance totale est égale à la somme des variances sur chacune des communes.

# II. Estimation de la variance d’un ratio

L’estimation de la variance d’un ratio $Z1 \over Z2$, on passe par la variable linéarisée : 

(3) $U = (Z1 - R Z2) / {\hat T}_{Z2}$ où $R = {{\hat T}_{Z1} \over {\hat T}_{Z2}}$ 
à laquelle on applique la formule du total précédente.

# III. Estimation par le ratio d’un total

L’estimation par le ratio que l’on applique à l’ensemble restreint des adresses à probabilités égale à 2,5 :

(4) ${\hat T}_{Z_ration} = {\hat T}_{ Z } \times {T_{X ril1_[zone]} / T_{X ril} \over {{\hat T}_{X rp{1[zone]}} / {\hat T}_{X rp}} } =  {{\hat T}_{ Z } \over {\hat T}_{X rp_[zone]}} \times T_{X_[zone] theorique}$ 

Dans une estimation par le ratio classique, le nombre total de logements par communes dans le RP se cale sur le nombre (considéré comme la **vraie valeur**) du RIL. Or, comme le RP a déjà été calé au niveau logement par commune, on ne cherche donc qu’à corriger la structure et non la taille. De plus, on fait l’hypothèse que $T_{X rp}$ est un total connu au mème titre que les totaux originaires du RIL afin de créer un $T_X$ théorique (ne dépendant pas du tirage aléatoire) afin de calculer la variance.

(5)  $U = ( Z - R X )$ où $R = {{\hat T}_{ Z } \over {\hat T}_{X rp_[zone]}}$

Cette méthode par le ratio modifié sert à résoudre le problème des différences entre le RP et le RIL (le RIL étant valable **avant** la collecte et le RP **après**).

Les totaux utilisés pour calculer $R$ sont sur l'ensemble de la zone (i.e. et non par rapport à la commune ou le groupe de rotation) (cf Pascal ARDILLY, technique de sondage p. 305)

# IV. Effet de l’estimation par le ratio

Cette estimation divise par environs 2 les écart-types des estimateurs (de - 30 % à - 85 %) . Dans la plupart des cas, le nouvel intervalle de confiance est contenu dans l’ancien.
Néanmoins, la somme des totaux de population par commune est transformée légèrement en fonction du découpage. Par exemple, avec le découpage en QPV, il y a une perte de 356 habitants sur l’ensemble des communes abritant un QPV (538 025 -> 537 669)



